import { TextStyle } from '../types';

export const textStyles: { [key: string]: TextStyle } = {
  'Elegante Superior': {
    font: 'bold 60px "Merriweather", serif',
    fillStyle: 'white',
    textAlign: 'center',
    textBaseline: 'top',
    position: { x: 0.5, y: 0.05 },
    shadowColor: 'rgba(0,0,0,0.5)',
    shadowBlur: 10,
    shadowOffsetX: 2,
    shadowOffsetY: 2,
    maxWidthFactor: 0.8,
  },
  'Moderno Inferior': {
    font: '800 70px "Montserrat", sans-serif',
    fillStyle: '#FFFFFF',
    textAlign: 'center',
    textBaseline: 'bottom',
    position: { x: 0.5, y: 0.95 },
    shadowColor: 'rgba(0,0,0,0.7)',
    shadowBlur: 15,
    shadowOffsetX: 0,
    shadowOffsetY: 5,
    strokeColor: 'black',
    strokeWidth: 2,
    maxWidthFactor: 0.9,
  },
  'Promoción Esquina': {
    font: 'italic bold 50px "Roboto", sans-serif',
    fillStyle: '#FFD700',
    textAlign: 'left',
    textBaseline: 'top',
    position: { x: 0.05, y: 0.05 },
    strokeColor: '#A0522D',
    strokeWidth: 3,
    maxWidthFactor: 0.4,
  },
   'Central Impacto': {
    font: '900 90px "Impact", sans-serif',
    fillStyle: 'rgba(255, 255, 255, 0.9)',
    textAlign: 'center',
    textBaseline: 'middle',
    position: { x: 0.5, y: 0.5 },
    shadowColor: 'black',
    shadowBlur: 5,
    shadowOffsetX: 5,
    shadowOffsetY: 5,
    strokeColor: 'black',
    strokeWidth: 2,
    maxWidthFactor: 0.7,
  },
   'Minimalista Derecha': {
    font: '300 45px "Lato", sans-serif',
    fillStyle: '#333333',
    textAlign: 'right',
    textBaseline: 'bottom',
    position: { x: 0.95, y: 0.95 },
    maxWidthFactor: 0.5,
  },
  'Neón Eléctrico': {
    font: 'bold 75px "Audiowide", cursive',
    fillStyle: '#FFFFFF',
    textAlign: 'center',
    textBaseline: 'middle',
    position: { x: 0.5, y: 0.5 },
    shadowColor: '#00FFFF',
    shadowBlur: 20,
    strokeColor: '#00FFFF',
    strokeWidth: 2,
    maxWidthFactor: 0.8,
  },
  'Retro Pop': {
    font: 'bold 80px "Bangers", cursive',
    fillStyle: '#FFC700',
    textAlign: 'center',
    textBaseline: 'middle',
    position: { x: 0.5, y: 0.85 },
    strokeColor: '#DA2C2C',
    strokeWidth: 6,
    shadowColor: 'black',
    shadowOffsetX: 5,
    shadowOffsetY: 5,
    maxWidthFactor: 0.8,
  },
  'Lujo Dorado': {
    font: 'normal 60px "Great Vibes", cursive',
    fillStyle: { gradient: ['#B48811', '#F0E68C', '#B48811'] },
    textAlign: 'center',
    textBaseline: 'middle',
    position: { x: 0.5, y: 0.2 },
    shadowColor: 'rgba(0,0,0,0.4)',
    shadowBlur: 5,
    shadowOffsetX: 2,
    shadowOffsetY: 2,
    maxWidthFactor: 0.7,
  }
};